In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('train.txt',sep = ';',header = None,names = ['text','emotion'])

In [3]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [4]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [6]:
unique_emotions = df['emotion'].unique()
unique_emotions

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

##oputput converts numbers

In [7]:
emotion_numbers = {}
i = 0
for emo in unique_emotions:
  emotion_numbers[emo] = i
  i +=1

df['emotion'] = df['emotion'].map(emotion_numbers)

In [8]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        0
1  i can go from feeling so hopeless to so damned...        0
2   im grabbing a minute to post i feel greedy wrong        1
3  i am ever feeling nostalgic about the fireplac...        2
4                               i am feeling grouchy        1

## convert Lowercase Letter

In [9]:
df['text'] = df['text'].apply(lambda x : x.lower())

## remove punctuation

In [10]:
import string

def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

In [11]:
df['text'] = df['text'].apply(remove_punc)

## remove numbers

In [12]:
def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

df['text'] = df['text'].apply(remove_numbers)

#Remove HTML Tags, Links, Emojis

In [14]:
!pip install --no-cache-dir bnlp_toolkit beautifulsoup4 emoji

Collecting bnlp_toolkit
  Downloading bnlp_toolkit-4.4.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.13/dist-packages (4.13.5)
Collecting emoji
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: sentencepiece>=0.2.0 in /usr/local/lib/python3.13/dist-packages (from bnlp_toolkit) (0.2.2)
Collecting gensim>=4.3.3 (from bnlp_toolkit)
  Downloading gensim-4.4.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: nltk in /usr/local/lib/python3.13/dist-packages (from bnlp_toolkit) (3.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from bnlp_toolkit) (2.1.3)
Requirement already satisfied: scipy>=1.11.0 in /usr/local/lib/python3.13/dist-packages (from bnlp_toolkit) (1.16.3)
Collecting sklearn-crfsuite>=0.5.0 (from bnlp_toolkit)
  Downloading sklearn_crfsuite-0.5.0-py2.py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.13/dist-packages (from bnlp_toolkit) (4.67.3)
Collecting ftfy>=6.2.0 (from bnlp_toolkit)
  Downloading ftfy-6.3.1-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.13/dist-packages (from bnlp_toolkit) (2.32.4)
Collecting symspellpy>=6.7.0 (from bnlp_toolkit)
  Downloading symspellpy-6.10.0-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (2.9.2)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4) (4.16.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.13/dist-packages (from ftfy>=6.2.0->bnlp_toolkit) (0.8.2)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.13/dist-packages (from gensim>=4.3.3->bnlp_toolkit) (8.0.1)
Collecting python-crfsuite>=0.9.7 (from sklearn-crfsuite>=0.5.0->bnlp_toolkit)
  Downloading python_crfsuite-0.9.12-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (4.3 kB)
Requirement already satisfied: scikit-learn>=0.24.0 in /usr/local/lib/python3.13/dist-packages (from sklearn-crfsuite>=0.5.0->bnlp_toolkit) (1.6.1)
Requirement already satisfied: tabulate>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from sklearn-crfsuite>=0.5.0->bnlp_toolkit) (0.9.0)
Requirement already satisfied: click in /usr/local/lib/python3.13/dist-packages (from nltk->bnlp_toolkit) (8.5.0)
Requirement already satisfied: joblib in /usr/local/lib/python3.13/dist-packages (from nltk->bnlp_toolkit) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.13/dist-packages (from nltk->bnlp_toolkit) (2025.11.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests->bnlp_toolkit) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests->bnlp_toolkit) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests->bnlp_toolkit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests->bnlp_toolkit) (2026.7.22)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=0.24.0->sklearn-crfsuite>=0.5.0->bnlp_toolkit) (3.6.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.13/dist-packages (from smart_open>=1.8.1->gensim>=4.3.3->bnlp_toolkit) (2.3.0)
Downloading bnlp_toolkit-4.4.1-py3-none-any.whl (68 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.6/68.6 kB 6.5 MB/s eta 0:00:00
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 24.2 MB/s eta 0:00:00
Downloading ftfy-6.3.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 220.2 MB/s eta 0:00:00
Downloading gensim-4.4.0-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.8/27.8 MB 137.6 MB/s eta 0:00:00
Downloading sklearn_crfsuite-0.5.0-py2.py3-none-any.whl (10 kB)
Downloading symspellpy-6.10.0-py3-none-any.whl (2.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 288.4 MB/s eta 0:00:00
Downloading python_crfsuite-0.9.12-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 319.4 MB/s eta 0:00:00
Installing collected packages: symspellpy, python-crfsuite, ftfy, emoji, gensim, sklearn-crfsuite, bnlp_toolkit
Successfully installed bnlp_toolkit-4.4.1 emoji-2.15.0 ftfy-6.3.1 gensim-4.4.0 python-crfsuite-0.9.12 sklearn-crfsuite-0.5.0 symspellpy-6.10.0

In [18]:
import emoji
from bs4 import BeautifulSoup
import re

In [16]:
def remove_html_tags(text):
    if not isinstance(text, str): return ""
    return BeautifulSoup(text, "html.parser").get_text()
df['text'] = df['text'].apply(remove_html_tags)

In [19]:
def remove_urls(text):
    return re.sub(r'https?://\S+|www\.\S+|ftp://\S+', '', text)
df['text'] = df['text'].apply(remove_urls)

In [20]:
def remove_emojicons(text):
    return emoji.replace_emoji(text, replace='')
df['text'] = df['text'].apply(remove_emojicons)

another way to remove imoji icon for english language are:

def remove_emojis(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new += i
    return new

df['text'] = df['text'].apply(remove_emojis)

# Tokenization and Remove Stop words

In [31]:
import nltk

In [32]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [37]:
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [38]:
stop_words = set(stopwords.words('english'))
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [39]:
def remove(txt):
  words = word_tokenize(txt)
  cleaned = []
  for i in words:
    if not i in stop_words:
      cleaned.append(i)

  return ' '.join(cleaned)

In [40]:
df['text'] = df['text'].apply(remove)

In [41]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [43]:
df.head()

                                                text  emotion
0                              didnt feel humiliated        0
1  go feeling hopeless damned hopeful around some...        0
2          im grabbing minute post feel greedy wrong        1
3  ever feeling nostalgic fireplace know still pr...        2
4                                    feeling grouchy        1

In [44]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.20, random_state=42)

# Using Bag of Words and Naive Bayes algo

In [45]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)


nb_model = MultinomialNB()
nb_model.fit(X_train_bow, y_train)


pred_bow = nb_model.predict(X_test_bow)
print(accuracy_score(y_test, pred_bow))

0.7678125

#Using TFIDF and Naive Bayes algo

In [46]:
tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)


nb2_model = MultinomialNB()
nb2_model.fit(X_train_tfidf,y_train)

MultinomialNB()

In [47]:
y_pred = nb2_model.predict(X_test_tfidf)
print(accuracy_score(y_test, y_pred))

0.6609375

#Using Bag of Words and Logistic Regression

In [50]:
from sklearn.linear_model import LogisticRegression
Log_reg_1_model = LogisticRegression(max_iter=1000)
Log_reg_1_model.fit(X_train_bow, y_train)

LogisticRegression(max_iter=1000)

In [51]:
Log_reg_1_pred = Log_reg_1_model.predict(X_test_bow)
print(accuracy_score(y_test, Log_reg_1_pred))

0.88875

#Using TFIDF and Logistic Regression

In [52]:
Log_reg_2_model = LogisticRegression(max_iter=1000)
Log_reg_2_model.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=1000)

In [53]:
Log_reg_2_pred = Log_reg_2_model.predict(X_test_bow)
print(accuracy_score(y_test, Log_reg_2_pred))

0.848125