In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv('covid_toy.csv')
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [4]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)

In [6]:
X_train

    age  gender  fever   cough       city
73   34    Male   98.0  Strong    Kolkata
40   49  Female  102.0    Mild      Delhi
84   69  Female   98.0  Strong     Mumbai
68   54  Female  104.0  Strong    Kolkata
36   38  Female  101.0    Mild  Bangalore
..  ...     ...    ...     ...        ...
27   33  Female  102.0  Strong      Delhi
29   34  Female    NaN  Strong     Mumbai
86   25    Male  104.0    Mild  Bangalore
2    42    Male  101.0    Mild      Delhi
14   51    Male  104.0    Mild  Bangalore

[80 rows x 5 columns]

In [7]:
from sklearn.compose import ColumnTransformer

In [9]:
transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(), ['fever']),
    ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),
    ('tnf3', OneHotEncoder(sparse_output=False, drop='first'), ['gender', 'city']) # Updated here
], remainder='passthrough')

In [10]:
transformer.fit_transform(X_train).shape

(80, 7)

In [11]:
transformer.transform(X_test).shape

(20, 7)